[package]
name = "docker-backup"
version = "0.1.0"
authors = ["Hristo Kolev <hristo.a.kolev@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.13.0"
lettre = "0.9"
lettre_email = "0.9"
failure = "0.1.5"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
