[package]
name = "docker-backup"
version = "0.1.0"
authors = ["Hristo Kolev <hristo.a.kolev@gmail.com>"]
edition = "2018"

[dependencies]
lettre = "0.9"
lettre_email = "0.9"

serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"

failure = "0.1.5"

handlebars = "1.1.0"
